// Writes the MToon .fmat variants from tool/mtoon_template.fmat.
//
//   dart run tool/generate_mtoon.dart
//
// .fmat fixes blending, culling, and depth writes at compile time, so each
// combination MToon needs is its own material. lib/src/runtime/mtoon.dart
// picks one per glTF material.
import 'dart:io';

const variants = <(String, String, String, bool)>[
  // (file stem, blending, culling, depth write)
  ('mtoon_opaque', 'opaque', 'back', false),
  ('mtoon_opaque_double', 'opaque', 'none', false),
  ('mtoon_blend', 'alpha', 'back', false),
  ('mtoon_blend_double', 'alpha', 'none', false),
  ('mtoon_blend_zwrite', 'alpha', 'back', true),
  ('mtoon_blend_zwrite_double', 'alpha', 'none', true),
];

void main() {
  final template = File('tool/mtoon_template.fmat').readAsStringSync();
  Directory('assets/materials').createSync(recursive: true);
  for (final (stem, blending, culling, zwrite) in variants) {
    final name = stem
        .split('_')
        .map((w) => w[0].toUpperCase() + w.substring(1))
        .join();
    final out = template
        .replaceFirst(
          RegExp(r'^// MToon 1\.0.*?(?=\nmaterial \{)', dotAll: true),
          '// GENERATED by tool/generate_mtoon.dart from tool/mtoon_template.fmat.\n'
          '// Do not edit.',
        )
        .replaceAll('{{NAME}}', 'Vrm$name')
        .replaceAll('{{BLENDING}}', blending)
        .replaceAll('{{CULLING}}', culling)
        .replaceAll('{{DEPTH_WRITE}}', zwrite ? '\n  depth_write: true,' : '');
    File('assets/materials/$stem.fmat').writeAsStringSync(out);
    stdout.writeln('assets/materials/$stem.fmat');
  }
}
